---
name: "Auto-Merge"
description: "Enable auto-merge on a PR."
inputs:
  app_id:
    description: GitHub app ID
    required: true
  app_private_key:
    description: GitHub app ID
    required: true
  pr_url:
    description: Pull request HTML URL.
    default: ${{ github.event.pull_request.html_url }}

runs:
  using: composite
  steps:
    - name: Generate a token
      id: generate_token
      uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.app_private_key }}

    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Enable auto-merge
      shell: bash
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
