---
"on":
  push:
  pull_request:

env:
  TEST_PR_URL: https://github.com/devon-mar/auto-merge-action-test/pull/1
  TEST_REPO: devon-mar/auto-merge-action-test
  VIEW_COMMAND: gh pr view "$TEST_PR_URL" --json autoMergeRequest -t "{{ ne .autoMergeRequest nil }}"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TEST_APP_ID }}
          private_key: ${{ secrets.TEST_APP_PRIVATE_KEY }}
          repository: devon-mar/auto-merge-action-test

      - name: Disable auto merge on the PR
        run: |
          gh pr merge --disable-auto "$TEST_PR_URL"
          OUTPUT=`${{ env.VIEW_COMMAND }}`
          echo "$OUTPUT"
          [[ "$OUTPUT" = "false" ]]
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Run the action
        uses: ./
        with:
          app_id: ${{ secrets.TEST_APP_ID }}
          app_private_key: ${{ secrets.TEST_APP_PRIVATE_KEY }}
          pr_url: ${{ env.TEST_PR_URL }}
          repository: ${{ env.TEST_REPO }}

      - name: Assert that auto merge is enabled
        run: |
          OUTPUT=`${{ env.VIEW_COMMAND }}`
          echo "$OUTPUT"
          [[ "$OUTPUT" = "true" ]]
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
